import React, { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Database, Layout, Zap, ChevronRight, AlertCircle, CheckCircle, Sparkles } from "lucide-react";

export default function DependencyResolver({
  selectedEntities = [],
  availablePages = [],
  availableFeatures = [],
  onResolveDependencies
}) {
  const [suggestedPages, setSuggestedPages] = useState([]);
  const [suggestedFeatures, setSuggestedFeatures] = useState([]);
  const [autoGeneratePages, setAutoGeneratePages] = useState([]);
  const [selectedSuggestions, setSelectedSuggestions] = useState({
    pages: [],
    features: [],
    autoGenerate: []
  });

  useEffect(() => {
    resolveDependencies();
  }, [selectedEntities]);

  const resolveDependencies = () => {
    const entityNames = selectedEntities.map(e => e.name.toLowerCase());
    
    // Find pages that use selected entities
    const relatedPages = availablePages.filter(page => {
      const pageEntities = (page.entities_used || []).map(e => e.toLowerCase());
      return pageEntities.some(pe => entityNames.includes(pe));
    });
    setSuggestedPages(relatedPages);
    
    // Find features that use selected entities
    const relatedFeatures = availableFeatures.filter(feature => {
      const featureEntities = (feature.entities_used || []).map(e => e.toLowerCase());
      return featureEntities.some(fe => entityNames.includes(fe));
    });
    setSuggestedFeatures(relatedFeatures);
    
    // Suggest auto-generated CRUD pages for entities without pages
    const entitiesWithoutPages = selectedEntities.filter(entity => {
      const hasPage = relatedPages.some(page => 
        (page.entities_used || []).map(e => e.toLowerCase()).includes(entity.name.toLowerCase())
      );
      return !hasPage;
    });
    
    const autoGenPages = entitiesWithoutPages.map(entity => ({
      entity: entity.name,
      pages: [
        { type: "list", name: `${entity.name} List`, description: `List all ${entity.name} records` },
        { type: "detail", name: `${entity.name} Detail`, description: `View ${entity.name} details` },
        { type: "form", name: `${entity.name} Form`, description: `Create/Edit ${entity.name}` }
      ]
    }));
    setAutoGeneratePages(autoGenPages);
    
    // Pre-select all suggestions
    setSelectedSuggestions({
      pages: relatedPages.map(p => p.id || p.name),
      features: relatedFeatures.map(f => f.id || f.name),
      autoGenerate: autoGenPages.flatMap(ag => ag.pages.map(p => `${ag.entity}-${p.type}`))
    });
  };

  const toggleSelection = (type, id) => {
    setSelectedSuggestions(prev => ({
      ...prev,
      [type]: prev[type].includes(id)
        ? prev[type].filter(i => i !== id)
        : [...prev[type], id]
    }));
  };

  const handleApply = () => {
    const resolvedPages = suggestedPages.filter(p => 
      selectedSuggestions.pages.includes(p.id || p.name)
    );
    
    const resolvedFeatures = suggestedFeatures.filter(f => 
      selectedSuggestions.features.includes(f.id || f.name)
    );
    
    const resolvedAutoGen = autoGeneratePages.flatMap(ag => 
      ag.pages
        .filter(p => selectedSuggestions.autoGenerate.includes(`${ag.entity}-${p.type}`))
        .map(p => ({ ...p, entity: ag.entity }))
    );
    
    onResolveDependencies({
      pages: resolvedPages,
      features: resolvedFeatures,
      autoGeneratedPages: resolvedAutoGen
    });
  };

  const totalSuggestions = suggestedPages.length + suggestedFeatures.length + 
    autoGeneratePages.reduce((sum, ag) => sum + ag.pages.length, 0);

  if (totalSuggestions === 0) {
    return (
      <Card className="bg-[var(--color-success)]/10 border-[var(--color-success)]/30">
        <CardContent className="pt-4 flex items-center gap-3">
          <CheckCircle className="h-5 w-5 text-[var(--color-success)]" />
          <span className="text-[var(--color-success-dark)]">No additional dependencies found</span>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-[var(--color-warning)]/30 bg-[var(--color-warning)]/10">
      <CardHeader className="pb-2">
        <CardTitle className="text-base flex items-center gap-2 text-[var(--color-midnight)]">
          <AlertCircle className="h-5 w-5 text-[var(--color-warning)]" />
          Dependency Suggestions
        </CardTitle>
        <p className="text-sm text-[var(--color-charcoal)]">
          Based on selected entities, we suggest including these items:
        </p>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="pages">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="pages" className="text-xs">
              <Layout className="h-3 w-3 mr-1" />
              Pages ({suggestedPages.length})
            </TabsTrigger>
            <TabsTrigger value="features" className="text-xs">
              <Zap className="h-3 w-3 mr-1" />
              Features ({suggestedFeatures.length})
            </TabsTrigger>
            <TabsTrigger value="autogen" className="text-xs">
              <Sparkles className="h-3 w-3 mr-1" />
              Auto-Gen ({autoGeneratePages.length})
            </TabsTrigger>
          </TabsList>

          <TabsContent value="pages">
            <ScrollArea className="h-48">
              <div className="space-y-2">
                {suggestedPages.map(page => (
                  <div key={page.id || page.name} className="flex items-center gap-3 p-2 bg-[var(--color-background-paper)] rounded">
                    <Checkbox
                      checked={selectedSuggestions.pages.includes(page.id || page.name)}
                      onCheckedChange={() => toggleSelection('pages', page.id || page.name)}
                    />
                    <div className="flex-1">
                      <span className="font-medium text-sm text-[var(--color-midnight)]">{page.name}</span>
                      <p className="text-xs text-[var(--color-charcoal)]">{page.description}</p>
                    </div>
                    <Badge variant="outline" className="text-xs">{page.category}</Badge>
                  </div>
                ))}
                {suggestedPages.length === 0 && (
                  <p className="text-sm text-[var(--color-charcoal)] text-center py-4">No page suggestions</p>
                )}
              </div>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="features">
            <ScrollArea className="h-48">
              <div className="space-y-2">
                {suggestedFeatures.map(feature => (
                  <div key={feature.id || feature.name} className="flex items-center gap-3 p-2 bg-[var(--color-background-paper)] rounded">
                    <Checkbox
                      checked={selectedSuggestions.features.includes(feature.id || feature.name)}
                      onCheckedChange={() => toggleSelection('features', feature.id || feature.name)}
                    />
                    <div className="flex-1">
                      <span className="font-medium text-sm text-[var(--color-midnight)]">{feature.name}</span>
                      <p className="text-xs text-[var(--color-charcoal)]">{feature.description}</p>
                    </div>
                    <Badge variant="outline" className="text-xs">{feature.complexity}</Badge>
                  </div>
                ))}
                {suggestedFeatures.length === 0 && (
                  <p className="text-sm text-[var(--color-charcoal)] text-center py-4">No feature suggestions</p>
                )}
              </div>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="autogen">
            <ScrollArea className="h-48">
              <div className="space-y-3">
                {autoGeneratePages.map(ag => (
                  <div key={ag.entity} className="bg-[var(--color-background-paper)] rounded p-2">
                    <div className="flex items-center gap-2 mb-2">
                      <Database className="h-4 w-4 text-[var(--color-primary)]" />
                      <span className="font-medium text-sm text-[var(--color-midnight)]">{ag.entity}</span>
                      <Badge className="bg-[var(--color-accent)]/20 text-[var(--color-accent-dark)] text-xs">CRUD</Badge>
                    </div>
                    <div className="ml-6 space-y-1">
                      {ag.pages.map(page => (
                        <div key={`${ag.entity}-${page.type}`} className="flex items-center gap-2">
                          <Checkbox
                            checked={selectedSuggestions.autoGenerate.includes(`${ag.entity}-${page.type}`)}
                            onCheckedChange={() => toggleSelection('autoGenerate', `${ag.entity}-${page.type}`)}
                          />
                          <span className="text-xs">{page.name}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
                {autoGeneratePages.length === 0 && (
                  <p className="text-sm text-[var(--color-charcoal)] text-center py-4">All entities have associated pages</p>
                )}
              </div>
            </ScrollArea>
          </TabsContent>
        </Tabs>

        <div className="flex justify-end gap-2 mt-4">
          <Button variant="outline" size="sm" onClick={() => setSelectedSuggestions({ pages: [], features: [], autoGenerate: [] })}>
            Clear All
          </Button>
          <Button size="sm" onClick={handleApply} className="bg-[var(--color-primary)] hover:bg-[var(--color-primary-dark)] text-white">
            Apply Selected
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}