import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { base44 } from "@/api/base44Client";
import { Copy, Check, Sparkles, Upload, Save, X, Loader2, RefreshCw } from "lucide-react";

export default function OklchPaletteTool({ onSave, brandColors: initialBrandColors }) {
  const [baseColor, setBaseColor] = useState({ l: 0.6, c: 0.15, h: 180 });
  const [paletteType, setPaletteType] = useState("monochromatic");
  const [colorCount, setColorCount] = useState(5);
  const [colors, setColors] = useState([]);
  const [paletteName, setPaletteName] = useState("");
  const [paletteDescription, setPaletteDescription] = useState("");
  const [paletteTags, setPaletteTags] = useState([]);
  const [tagInput, setTagInput] = useState("");
  const [aiPrompt, setAiPrompt] = useState("");
  const [brandColors, setBrandColors] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(null);
  const [showLibrary, setShowLibrary] = useState(!initialBrandColors);
  const [hasAutoGenerated, setHasAutoGenerated] = React.useState(false);
  
  // Auto-generate from brand colors on mount
  React.useEffect(() => {
    if (initialBrandColors && !hasAutoGenerated) {
      const colorsString = [
        initialBrandColors.primary,
        initialBrandColors.secondary,
        initialBrandColors.accent
      ].filter(Boolean).join(", ");
      
      if (colorsString) {
        setBrandColors(colorsString);
        setHasAutoGenerated(true);
        generateFromBrandColorsAuto(colorsString);
      }
    }
  }, [initialBrandColors, hasAutoGenerated]);
  
  const generateFromBrandColorsAuto = async (colorsStr) => {
    setIsGenerating(true);
    try {
      const prompt = `Create a harmonious color palette of ${colorCount} colors based on these brand colors: ${colorsStr}. Return JSON with: name, description, colors array (each with name, lightness 0-1, chroma 0-0.4, hue 0-360).`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            name: { type: "string" },
            description: { type: "string" },
            colors: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  lightness: { type: "number" },
                  chroma: { type: "number" },
                  hue: { type: "number" }
                }
              }
            }
          }
        }
      });
      if (result.colors) {
        setPaletteName(result.name || "Brand Palette");
        setPaletteDescription(result.description || "");
        setColors(result.colors.map(c => ({
          l: c.lightness,
          c: c.chroma,
          h: c.hue,
          name: c.name
        })));
      }
    } catch (e) {
      console.error("AI brand palette failed:", e);
    }
    setIsGenerating(false);
  };
  
  const oklchToRgb = (l, c, h) => {
    const a = c * Math.cos((h * Math.PI) / 180);
    const b = c * Math.sin((h * Math.PI) / 180);
    
    const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
    const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
    const s_ = l - 0.0894841775 * a - 1.2914855480 * b;
    
    const l3 = l_ * l_ * l_;
    const m3 = m_ * m_ * m_;
    const s3 = s_ * s_ * s_;
    
    let r = +4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3;
    let g = -1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3;
    let bl = -0.0041960863 * l3 - 0.7034186147 * m3 + 1.7076147010 * s3;
    
    r = r > 0.0031308 ? 1.055 * Math.pow(r, 1 / 2.4) - 0.055 : 12.92 * r;
    g = g > 0.0031308 ? 1.055 * Math.pow(g, 1 / 2.4) - 0.055 : 12.92 * g;
    bl = bl > 0.0031308 ? 1.055 * Math.pow(bl, 1 / 2.4) - 0.055 : 12.92 * bl;
    
    r = Math.max(0, Math.min(255, Math.round(r * 255)));
    g = Math.max(0, Math.min(255, Math.round(g * 255)));
    bl = Math.max(0, Math.min(255, Math.round(bl * 255)));
    
    return "#" + [r, g, bl].map(x => x.toString(16).padStart(2, "0")).join("");
  };
  
  const generatePalette = () => {
    const palette = [];
    const { l, c, h } = baseColor;
    
    if (paletteType === "monochromatic") {
      for (let i = 0; i < colorCount; i++) {
        const lightness = 0.2 + (0.8 / (colorCount - 1)) * i;
        palette.push({ l: lightness, c, h, name: `Shade ${i + 1}` });
      }
    } else if (paletteType === "analogous") {
      const spread = 30;
      for (let i = 0; i < colorCount; i++) {
        const hueShift = -spread + (spread * 2 / (colorCount - 1)) * i;
        palette.push({ l, c, h: (h + hueShift + 360) % 360, name: `Color ${i + 1}` });
      }
    } else if (paletteType === "complementary") {
      palette.push({ l, c, h, name: "Base" });
      palette.push({ l, c, h: (h + 180) % 360, name: "Complement" });
      if (colorCount > 2) {
        for (let i = 2; i < colorCount; i++) {
          const lightness = 0.3 + (0.6 / (colorCount - 2)) * (i - 2);
          palette.push({ l: lightness, c: c * 0.5, h, name: `Tint ${i - 1}` });
        }
      }
    } else if (paletteType === "triadic") {
      palette.push({ l, c, h, name: "Base" });
      palette.push({ l, c, h: (h + 120) % 360, name: "Triadic 1" });
      palette.push({ l, c, h: (h + 240) % 360, name: "Triadic 2" });
      if (colorCount > 3) {
        for (let i = 3; i < colorCount; i++) {
          const lightness = 0.3 + (0.6 / (colorCount - 3)) * (i - 3);
          palette.push({ l: lightness, c: c * 0.6, h, name: `Tint ${i - 2}` });
        }
      }
    } else if (paletteType === "split-complementary") {
      palette.push({ l, c, h, name: "Base" });
      palette.push({ l, c, h: (h + 150) % 360, name: "Split 1" });
      palette.push({ l, c, h: (h + 210) % 360, name: "Split 2" });
      if (colorCount > 3) {
        for (let i = 3; i < colorCount; i++) {
          const lightness = 0.3 + (0.6 / (colorCount - 3)) * (i - 3);
          palette.push({ l: lightness, c: c * 0.5, h, name: `Tint ${i - 2}` });
        }
      }
    }
    
    setColors(palette);
  };
  
  React.useEffect(() => {
    generatePalette();
  }, [baseColor, paletteType, colorCount]);
  
  const copyColor = (color, format) => {
    let text = "";
    if (format === "oklch") {
      text = `oklch(${color.l.toFixed(3)} ${color.c.toFixed(3)} ${color.h.toFixed(1)})`;
    } else {
      text = oklchToRgb(color.l, color.c, color.h);
    }
    navigator.clipboard.writeText(text);
    setCopied(`${format}-${color.name}`);
    setTimeout(() => setCopied(null), 2000);
  };

  const generateAINames = async () => {
    setIsGenerating(true);
    try {
      const prompt = `Generate creative, descriptive names for these colors: ${colors.map((c, i) => `Color ${i + 1}: oklch(${c.l.toFixed(3)} ${c.c.toFixed(3)} ${c.h.toFixed(1)})`).join(", ")}. Return a JSON array of names only.`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: { type: "object", properties: { names: { type: "array", items: { type: "string" } } } }
      });
      if (result.names) {
        setColors(colors.map((c, i) => ({ ...c, name: result.names[i] || c.name })));
      }
    } catch (e) {
      console.error("AI naming failed:", e);
    }
    setIsGenerating(false);
  };

  const generateAITags = async () => {
    setIsGenerating(true);
    try {
      const prompt = `Generate 3-5 relevant tags for a color palette with these colors: ${colors.map(c => c.name).join(", ")}. Consider mood, style, use case. Return a JSON array of lowercase tags.`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: { type: "object", properties: { tags: { type: "array", items: { type: "string" } } } }
      });
      if (result.tags) {
        setPaletteTags(result.tags);
      }
    } catch (e) {
      console.error("AI tag generation failed:", e);
    }
    setIsGenerating(false);
  };

  const generateFromPrompt = async () => {
    if (!aiPrompt.trim()) return;
    setIsGenerating(true);
    try {
      const prompt = `Create a color palette based on: "${aiPrompt}". Generate ${colorCount} colors in OKLCH format. Return JSON with: name, description, colors array (each with name, lightness 0-1, chroma 0-0.4, hue 0-360).`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            name: { type: "string" },
            description: { type: "string" },
            colors: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  lightness: { type: "number" },
                  chroma: { type: "number" },
                  hue: { type: "number" }
                }
              }
            }
          }
        }
      });
      if (result.colors) {
        setPaletteName(result.name || aiPrompt);
        setPaletteDescription(result.description || "");
        setColors(result.colors.map(c => ({
          l: c.lightness,
          c: c.chroma,
          h: c.hue,
          name: c.name
        })));
      }
    } catch (e) {
      console.error("AI palette generation failed:", e);
    }
    setIsGenerating(false);
  };

  const generateFromBrandColors = async () => {
    if (!brandColors.trim()) return;
    setIsGenerating(true);
    try {
      const prompt = `Create a harmonious color palette of ${colorCount} colors based on these brand colors: ${brandColors}. Return JSON with: name, description, colors array (each with name, lightness 0-1, chroma 0-0.4, hue 0-360).`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: {
          type: "object",
          properties: {
            name: { type: "string" },
            description: { type: "string" },
            colors: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  lightness: { type: "number" },
                  chroma: { type: "number" },
                  hue: { type: "number" }
                }
              }
            }
          }
        }
      });
      if (result.colors) {
        setPaletteName(result.name || "Brand Palette");
        setPaletteDescription(result.description || "");
        setColors(result.colors.map(c => ({
          l: c.lightness,
          c: c.chroma,
          h: c.hue,
          name: c.name
        })));
      }
    } catch (e) {
      console.error("AI brand palette failed:", e);
    }
    setIsGenerating(false);
  };

  const handlePhotoUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    setIsGenerating(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      const prompt = `Analyze this image and extract a harmonious color palette of ${colorCount} colors. Return JSON with: name, description, colors array (each with name, lightness 0-1, chroma 0-0.4, hue 0-360).`;
      const result = await base44.integrations.Core.InvokeLLM({
        prompt,
        file_urls: [file_url],
        response_json_schema: {
          type: "object",
          properties: {
            name: { type: "string" },
            description: { type: "string" },
            colors: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  lightness: { type: "number" },
                  chroma: { type: "number" },
                  hue: { type: "number" }
                }
              }
            }
          }
        }
      });
      if (result.colors) {
        setPaletteName(result.name || "Photo Palette");
        setPaletteDescription(result.description || "");
        setColors(result.colors.map(c => ({
          l: c.lightness,
          c: c.chroma,
          h: c.hue,
          name: c.name
        })));
      }
    } catch (e) {
      console.error("Photo analysis failed:", e);
    }
    setIsGenerating(false);
  };

  const addTag = () => {
    if (tagInput.trim() && !paletteTags.includes(tagInput.trim())) {
      setPaletteTags([...paletteTags, tagInput.trim()]);
      setTagInput("");
    }
  };

  const removeTag = (tag) => {
    setPaletteTags(paletteTags.filter(t => t !== tag));
  };
  
  const handleSave = () => {
    if (onSave && paletteName && colors.length > 0) {
      const paletteData = {
        name: paletteName,
        description: paletteDescription,
        category: "palette",
        colors: colors.map(color => ({
          name: color.name,
          oklch: `oklch(${color.l.toFixed(3)} ${color.c.toFixed(3)} ${color.h.toFixed(1)})`,
          hex: oklchToRgb(color.l, color.c, color.h)
        })),
        tags: paletteTags.length > 0 ? paletteTags : [paletteType]
      };
      onSave(paletteData);
      setPaletteName("");
      setPaletteDescription("");
      setPaletteTags([]);
    }
  };
  
  return (
    <div className="space-y-6">
      {!initialBrandColors && (
        <Card className="rounded-xl bg-muted/50">
          <CardContent className="pt-6">
            <div className="text-center space-y-3">
              <p className="text-sm text-muted-foreground">
                No brand colors found. You can generate a palette using AI or select from the library.
              </p>
              <Button 
                variant="outline" 
                onClick={() => setShowLibrary(!showLibrary)}
              >
                {showLibrary ? "Hide" : "Browse"} Color Library
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
      
      {showLibrary && !initialBrandColors && (
        <Card className="rounded-xl">
          <CardHeader>
            <CardTitle>Select from Library</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Switch to the "Library" tab to browse and select existing color palettes.
            </p>
          </CardContent>
        </Card>
      )}
      
      <Card className="rounded-xl">
        <CardHeader>
          <CardTitle>AI Palette Generation</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label>Generate from Prompt</Label>
            <div className="flex gap-2">
              <Textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g., Modern tech startup, Ocean sunset, Vintage coffee shop..."
                rows={2}
                className="flex-1"
              />
              <Button onClick={generateFromPrompt} disabled={isGenerating || !aiPrompt.trim()}>
                {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Generate from Brand Colors</Label>
            <div className="flex gap-2">
              <Input
                value={brandColors}
                onChange={(e) => setBrandColors(e.target.value)}
                placeholder="e.g., #FF5733, #3498DB, sage green..."
              />
              <Button onClick={generateFromBrandColors} disabled={isGenerating || !brandColors.trim()}>
                {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Upload Photo for Palette</Label>
            <Input
              type="file"
              accept="image/*"
              onChange={handlePhotoUpload}
              disabled={isGenerating}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Manual Palette Generator</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div 
            className="w-full h-24 rounded-lg border-2 border-border"
            style={{ backgroundColor: oklchToRgb(baseColor.l, baseColor.c, baseColor.h) }}
          />
          
          <div className="space-y-3">
            <div className="space-y-2">
              <div className="flex justify-between">
                <Label className="text-xs">Lightness</Label>
                <span className="text-xs text-muted-foreground">{baseColor.l.toFixed(2)}</span>
              </div>
              <Slider 
                value={[baseColor.l * 100]} 
                onValueChange={([val]) => setBaseColor({...baseColor, l: val / 100})}
                min={0}
                max={100}
                step={1}
              />
            </div>
            
            <div className="space-y-2">
              <div className="flex justify-between">
                <Label className="text-xs">Chroma</Label>
                <span className="text-xs text-muted-foreground">{baseColor.c.toFixed(2)}</span>
              </div>
              <Slider 
                value={[baseColor.c * 250]} 
                onValueChange={([val]) => setBaseColor({...baseColor, c: val / 250})}
                min={0}
                max={100}
                step={1}
              />
            </div>
            
            <div className="space-y-2">
              <div className="flex justify-between">
                <Label className="text-xs">Hue</Label>
                <span className="text-xs text-muted-foreground">{baseColor.h.toFixed(0)}°</span>
              </div>
              <Slider 
                value={[baseColor.h]} 
                onValueChange={([val]) => setBaseColor({...baseColor, h: val})}
                min={0}
                max={360}
                step={1}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Type</Label>
              <Select value={paletteType} onValueChange={setPaletteType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="monochromatic">Monochromatic</SelectItem>
                  <SelectItem value="analogous">Analogous</SelectItem>
                  <SelectItem value="complementary">Complementary</SelectItem>
                  <SelectItem value="triadic">Triadic</SelectItem>
                  <SelectItem value="split-complementary">Split Complementary</SelectItem>
                </SelectContent>
              </Select>
            </div>
            
            <div className="space-y-2">
              <Label>Color Count</Label>
              <Input 
                type="number" 
                value={colorCount} 
                onChange={(e) => setColorCount(Math.max(2, Math.min(10, parseInt(e.target.value) || 5)))}
                min={2}
                max={10}
              />
            </div>
          </div>
          
          <Button onClick={generatePalette} variant="outline" className="w-full">
            <RefreshCw className="h-4 w-4 mr-2" /> Regenerate
          </Button>
        </CardContent>
      </Card>
      
      {colors.length > 0 && (
        <Card className="rounded-xl">
          <CardHeader className="flex flex-row items-center justify-between space-y-0">
            <CardTitle>Generated Palette</CardTitle>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={generateAINames} disabled={isGenerating}>
                <Sparkles className="h-4 w-4 mr-1" />AI Names
              </Button>
              <Button size="sm" variant="outline" onClick={generateAITags} disabled={isGenerating}>
                <Sparkles className="h-4 w-4 mr-1" />AI Tags
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            {colors.map((color, index) => (
              <div key={index} className="space-y-2">
                <div className="flex items-center gap-2">
                  <div 
                    className="h-12 flex-1 rounded border"
                    style={{ backgroundColor: oklchToRgb(color.l, color.c, color.h) }}
                  />
                  <Input
                    value={color.name}
                    onChange={(e) => {
                      const updated = [...colors];
                      updated[index].name = e.target.value;
                      setColors(updated);
                    }}
                    className="flex-1"
                  />
                  <div className="flex flex-col gap-1">
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => copyColor(color, "hex")}
                      className="h-7 px-2"
                    >
                      {copied === `hex-${color.name}` ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
                    </Button>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => copyColor(color, "oklch")}
                      className="h-7 px-2"
                    >
                      {copied === `oklch-${color.name}` ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
                    </Button>
                  </div>
                </div>
                <div className="text-xs text-muted-foreground font-mono">
                  {oklchToRgb(color.l, color.c, color.h)}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}
      
      {onSave && colors.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Save to Library</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Palette Name</Label>
              <Input 
                placeholder="e.g., Ocean Breeze" 
                value={paletteName}
                onChange={(e) => setPaletteName(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Description</Label>
              <Input
                value={paletteDescription}
                onChange={(e) => setPaletteDescription(e.target.value)}
                placeholder="e.g., Cool tones inspired by coastal waters"
              />
            </div>

            <div className="space-y-2">
              <Label>Tags</Label>
              <div className="flex gap-2">
                <Input
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && addTag()}
                  placeholder="Add tag..."
                />
                <Button onClick={addTag} size="sm">Add</Button>
              </div>
              <div className="flex flex-wrap gap-1 mt-2">
                {paletteTags.map(tag => (
                  <Badge key={tag} variant="secondary" className="gap-1">
                    {tag}
                    <X className="h-3 w-3 cursor-pointer" onClick={() => removeTag(tag)} />
                  </Badge>
                ))}
              </div>
            </div>

            <Button onClick={handleSave} className="w-full" disabled={!paletteName}>
              <Save className="h-4 w-4 mr-2" /> Save to Library
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}